openapi: 3.1.0
info:
  title: Eventify Estonia API
  description: API for managing events and processing user queries via Custom GPT.
  version: 1.0.2
servers:
  - url: https://zeya888.me/eventify.php
    description: Replit server handling GPT requests and event processing.

x-github-project: https://github.com/eslinko/eventizeya
$refs:
  descriptions: $x-github-project + './eventify-openai-schema-descriptions.md'
  semantic_guidelines: $x-github-project + './semantic-description-guidelines.md'
  euclidean_guidelines: $x-github-project + './euclidean-description-guidelines.md'

paths:
  /add-event:
    post:
      operationId: addEvent
      summary: Add a new event to the vector database
      description: $refs['descriptions#/add-event-post']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: $refs['descriptions#/name']
                desc_4_semantic:
                  type: string
                  description: $refs['semantic_guidelines#/desc_4_semantic']
                desc_4_euclidean:
                  type: string
                  description: $refs['euclidean_guidelines#/desc_4_euclidean']
                start_time:
                  type: string
                  format: date-time
                  description: $refs['descriptions#/start_time']
                end_time:
                  type: string
                  format: date-time
                  description: $refs['descriptions#/end_time']
                place:
                  type: object
                  description: $refs['descriptions#/place']
                  properties:
                    name:
                      type: string
                      description: $refs['descriptions#/place/name']
                    city:
                      type: string
                      description: $refs['descriptions#/place/city']
                    country:
                      type: string
                      description: $refs['descriptions#/place/country']
                    street:
                      type: string
                      description: $refs['descriptions#/place/street']
                format:
                  type: string
                  enum:
                    - Masterclass
                    - Regular
                    - Performance
                    - Exhibition
                    - Festival
                    - Dance
                    - Sound Healing
                    - Sacred Ceremony
                  description: $refs['descriptions#/format']
                contact_info:
                  type: object
                  description: $refs['descriptions#/contact_info']
                  properties:
                    phone:
                      type: string
                      description: $refs['descriptions#/contact_info/phone']
                    email:
                      type: string
                      description: $refs['descriptions#/contact_info/email']
                    telegram:
                      type: string
                      description: $refs['descriptions#/contact_info/telegram']
                    deso_alias:
                      type: string
                      description: $refs['descriptions#/contact_info/deso_alias']
                crypto_wallet:
                  type: object
                  description: $refs['descriptions#/crypto_wallet']
                  properties:
                    wallet_address:
                      type: string
                      description: $refs['descriptions#/crypto_wallet/wallet_address']
                    network:
                      type: string
                      description: $refs['descriptions#/crypto_wallet/network']
                external_links:
                  type: array
                  items:
                    type: string
                  description: $refs['descriptions#/external_links']
      responses:
        "200":
          description: $refs['descriptions#/event_added_success']
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Event added successfully
                  event_id:
                    type: string
                    description: $refs['descriptions#/event_id']
        "400":
          description: $refs['descriptions#/bad_request']
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: $refs['descriptions#/bad_request_message']
